services:
  postgres:
    image: postgres:17
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpass-123@
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: elestio/pgadmin:REL-9_0
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pguser@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: pgpass-strong-123@
    depends_on:
      - postgres

volumes:
  local_pgdata: